"""empty message

Revision ID: 0993904b27b7
Revises: 4b7b65baa11c
Create Date: 2025-04-08 23:29:10.957076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0993904b27b7'
down_revision = '4b7b65baa11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('shipment_status',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('shipment_status',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###
