"""empty message

Revision ID: 3e88eb81ac7c
Revises: 91b2c08f87c2
Create Date: 2025-04-06 14:12:22.993663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e88eb81ac7c'
down_revision = '91b2c08f87c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
