"""empty message

Revision ID: 5fcddbfe7c49
Revises: ccca152e4f17
Create Date: 2025-04-08 23:17:53.708970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcddbfe7c49'
down_revision = 'ccca152e4f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipment_status', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('shipment_status')

    # ### end Alembic commands ###
