"""empty message

Revision ID: a4516a05b670
Revises: 0993904b27b7
Create Date: 2025-04-09 22:31:35.344819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4516a05b670'
down_revision = '0993904b27b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userupload',
    sa.Column('upload_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_filename', sa.String(length=200), nullable=False),
    sa.Column('upload_desc', sa.String(length=500), nullable=False),
    sa.Column('upload_amt', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('upload_id')
    )
    with op.batch_alter_table('userupload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userupload_upload_amt'), ['upload_amt'], unique=False)
        batch_op.create_index(batch_op.f('ix_userupload_upload_desc'), ['upload_desc'], unique=False)
        batch_op.create_index(batch_op.f('ix_userupload_upload_filename'), ['upload_filename'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userupload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userupload_upload_filename'))
        batch_op.drop_index(batch_op.f('ix_userupload_upload_desc'))
        batch_op.drop_index(batch_op.f('ix_userupload_upload_amt'))

    op.drop_table('userupload')
    # ### end Alembic commands ###
