"""empty message

Revision ID: d7f46c845cde
Revises: 3e6ed1352c57
Create Date: 2025-04-06 14:18:21.818038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7f46c845cde'
down_revision = '3e6ed1352c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('filename')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('filename')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', mysql.VARCHAR(length=256), nullable=False))

    # ### end Alembic commands ###
