"""empty message

Revision ID: e9543b89a77f
Revises: d7f46c845cde
Create Date: 2025-04-06 14:29:18.002165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9543b89a77f'
down_revision = 'd7f46c845cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=688),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.String(length=688),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
