"""empty message

Revision ID: ee87edf71b52
Revises: d0aabfcc2561
Create Date: 2025-04-07 00:14:31.356013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee87edf71b52'
down_revision = 'd0aabfcc2561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_names', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('filename', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('filename')
        batch_op.drop_column('address')
        batch_op.drop_column('email')
        batch_op.drop_column('name')
        batch_op.drop_column('product_names')

    # ### end Alembic commands ###
